name: Benchmarks

on:
  workflow_run:
    workflows:
      - Tests
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: "Run benchmarks"
    runs-on: ubuntu-latest

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v3"
        with:
          python-version: 3.x

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip setuptools cython

      - name: "Build DAWG"
        run: |
          python setup.py build_ext --inplace

      - name: "Run benchmark"
        run: |
          echo '### Benchmark results' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          python -VV >> $GITHUB_STEP_SUMMARY
          python -m bench.speed >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
